apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - prefix: 1
        cluster: test
      - prefix: 2
        cluster: test
      - prefix: 3
        cluster: test
  template:
    metadata:
      name: 'guestbook-{{prefix}}-app'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/aborilov/argocd-example-apps/
        targetRevision: test
        path: guestbook
      destination:
        name: '{{cluster}}'
        namespace: akuity-poc-deployments
