apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-breaker
  namespace: chaos-loop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaos-breaker
  template:
    metadata:
      labels:
        app: chaos-breaker
    spec:
      serviceAccountName: chaos-hook
      containers:
        - name: breaker
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              while true; do
                kubectl delete configmap chaos-target -n chaos-loop --ignore-not-found
                sleep 5
              done
