apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-saboteur
  namespace: chaos-loop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaos-saboteur
  template:
    metadata:
      labels:
        app: chaos-saboteur
    spec:
      serviceAccountName: chaos-hook
      containers:
        - name: saboteur
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              while true; do
                kubectl delete pods -n chaos-loop -l app=chaos-target --ignore-not-found
                sleep 10
              done
