apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-target
  namespace: chaos-loop
spec:
  replicas: 5
  selector:
    matchLabels:
      app: chaos-target
  template:
    metadata:
      labels:
        app: chaos-target
    spec:
      containers:
        - name: target
          image: busybox:latest
          command: ["sh", "-c", "while true; do sleep 3600; done"]
